version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    command: sleep infinity
    volumes:
      - .:/workspace
    depends_on:
      - postgres
  postgres:
    image: postgres
    platform: linux/amd64
    tty: true
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./docker/postgres/pgdata:/var/lib/postgresql
      - ./init/postres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
